[versions]
loom = "1.4.+"
githubRelease = "2.4.1"
minotaur = "2.6.0"

mc = "1.19.2"
fl = "0.15.0"
yarn = "1.19.2+build.28"
fapi = "0.76.0+1.19.2"
kaleidoConfig = "0.2.0+1.2.0-beta.5"

emi = "1.0.4+1.19.2"

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
githubRelease = { id = "com.github.breadmoirai.github-release", version.ref = "githubRelease" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[libraries]
mc = { group = "mojang", name = "minecraft", version.ref = "mc" }
fl = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fl" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }
fapi = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fapi" }
kaleidoConfig = { group = "folk.sisby", name = "kaleido-config", version.ref = "kaleidoConfig" }

emi = { group = "dev.emi", name = "emi-fabric", version.ref = "emi" }
