[versions]
loom = "1.2.+"
githubRelease = "2.4.1"
minotaur = "2.6.0"

mc = "1.20.1"
ql = "0.19.0"
qm = "1.20.1+build.23"
fapi = "0.83.0-1.20"
qfapi = "7.0.2+0.83.0-1.20.1"

emi = "1.0.4+1.20.1"

[plugins]
loom = { id = "org.quiltmc.loom", version.ref = "loom" }
githubRelease = { id = "com.github.breadmoirai.github-release", version.ref = "githubRelease" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[libraries]
mc = { group = "mojang", name = "minecraft", version.ref = "mc" }
ql = { group = "org.quiltmc", name = "quilt-loader", version.ref = "ql" }
qm = { group = "org.quiltmc", name = "quilt-mappings", version.ref = "qm" }
qfapi = { group = "org.quiltmc.quilted-fabric-api", name = "quilted-fabric-api", version.ref = "qfapi" }

emi = { group = "dev.emi", name = "emi-fabric", version.ref = "emi" }
